[target.x86_64-unknown-linux-gnu]
image.name = "bmauto/eva4-cross-x86_64:latest"
#image.platform = "linux/amd64,linux/arm64"
image.toolchain = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

[target.aarch64-unknown-linux-gnu]
image.name = "bmauto/eva4-cross-aarch64:latest"
#image.platform = "linux/amd64,linux/arm64"
image.toolchain = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
