[package]
name = "eva-internal"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
aws-lc-rs = { workspace = true }
eva-common = { workspace = true, features = ["time", "extended-value"] }
tokio = { workspace = true, features = ["time", "rt"] }

