[package]
name = "eva-gst-pipeline"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-channel = { workspace = true }
async-trait = { workspace = true }
eva-common = { workspace = true, features = ["events", "common-payloads", "payload", "acl", "multimedia"] }
eva-sdk = { workspace = true, features = ["controller"] }
gstreamer = { version = "0.24" }
gstreamer-app = "0.24"
log = { workspace = true }
mimalloc = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
tokio = { workspace = true, features = ["full"] }

[features]
std-alloc = []
