[package]
name = "eva-svc-example-temp"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
eva-common = { version = "0.3", features = ["events", "common-payloads", "payload", "acl"] }
eva-sdk = { version = "0.3" }
tokio = { version = "1.36.0", features = ["full"] }
async-trait = { version = "0.1.77" }
serde = { version = "1.0.196", features = ["derive", "rc"] }
log = "0.4.20"
mimalloc = { version = "0.1.43" }
once_cell = "1.19.0"

[features]
std-alloc = []
