[package]
name = "eva-svc-example-temp"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
eva-common = { version = "0.4", features = ["events", "common-payloads", "payload", "acl"] }
eva-sdk = { version = "0.4" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive", "rc"] }
log = "0.4"
mimalloc = { version = "0.1" }

[features]
std-alloc = []
